/* eslint-disable no-shadow */
/* eslint-disable no-unused-vars */
export enum State {
  LOADING = "Loading",
  CHOOSING_MANIFEST = "Choosing manifest",
  CHOOSING_SEASON = "Choosing season",
  FINALIZING = "Finalizing",
  DOWNLOADING = "Downloading",
  DOWNLOAD_COMPLETE = "Download complete",
  DOWNLOAD_FAILED = "Download failed",
  DOWNLOAD_CANCELLED = "Download cancelled",
  DOWNLOAD_PAUSED = "Download paused",
}

export enum Method {
  SPLASH = "Splash",
  NATIVE = "Native",
  LOG = "Log (debug only)",
}

export const newManifests = {
  c1s2: {
    shortName: "c1s2",
    seasonName: "Season 2",
    icon: "c1s2p.jpg",
    banner: "c1s2b.png",
    manifests: [
      {
        name: "Cert-CL-3847564",
        version: "++Fortnite+Release-Cert-CL-3847564-Windows",
        id: "ZrI2-mGi5f095bc735dd412085dd6e71f5f1072f",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/ZrI2-mGi5f095bc735dd412085dd6e71f5f1072f.manifest",
        icon: "c1s2p.jpg",
        banner: "c1s2b.jfif",
      },
      {
        name: "2.5-CL-3889387",
        version: "++Fortnite+Release-2.5-CL-3889387-Windows",
        id: "d3s1TwNa7211302816b14cb28244998484a8be93",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/d3s1TwNa7211302816b14cb28244998484a8be93.manifest",
        icon: "c1s2p.jpg",
        banner: "c1s2b.jfif",
      },
    ],
  },
  c1s3: {
    shortName: "c1s3",
    seasonName: "Season 3",
    icon: "c1s3p.jpg",
    banner: "c1s3b.png",
    manifests: [
      {
        name: "3.0.0-CL-3901517",
        version: "++Fortnite+Release-3.0.0-CL-3901517-Windows",
        id: "k5ys7glx5bd3c57ec7b14db2bb69d44e16487a36",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/k5ys7glx5bd3c57ec7b14db2bb69d44e16487a36.manifest",
        icon: "c1s3p.jpg",
        banner: "c1s3b.jfif",
      },
      {
        name: "3.1-CL-3917250",
        version: "++Fortnite+Release-3.1-CL-3917250-Windows",
        id: "qSfz1yvL2a694c0e864a4e2aadd0229121cde46c",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/qSfz1yvL2a694c0e864a4e2aadd0229121cde46c.manifest",
        icon: "c1s3p.jpg",
        banner: "c1s3b.jfif",
      },
    ],
  },
  c1s4: {
    shortName: "c1s4",
    seasonName: "Season 4",
    icon: "c1s4p.jpg",
    banner: "c1s4b.png",
    manifests: [
      {
        name: "4.0-CL-4039451",
        version: "++Fortnite+Release-4.0-CL-4039451-Windows",
        id: "REvHap8Be76174fe73914ba99a652ef722c0bd8c",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/REvHap8Be76174fe73914ba99a652ef722c0bd8c.manifest",
        icon: "c1s4p.jpg",
        banner: "c1s4b.jfif",
      },
      {
        name: "4.1-CL-4053532",
        version: "++Fortnite+Release-4.1-CL-4053532-Windows",
        id: "LjhtJU7of2d3a380321f4257a791df5f165d1dea",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/LjhtJU7of2d3a380321f4257a791df5f165d1dea.manifest",
        icon: "c1s4p.jpg",
        banner: "c1s4b.jfif",
      },
    ],
  },
  c1s7: {
    shortName: "c1s7",
    seasonName: "Season 7",
    icon: "c1s7p.jpg",
    banner: "c1s7b.png",
    manifests: [
      {
        name: "7.30-CL-4834550",
        version: "++Fortnite+Release-7.30-CL-4834550-Windows",
        id: "8MYIDmwwomgXz_O0TUy0IC5y0ZUD-g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/8MYIDmwwomgXz_O0TUy0IC5y0ZUD-g.manifest",
        icon: "c1s7p.jpg",
        banner: "c1s7b.jfif",
      },
      {
        name: "7.40-CL-5046157",
        version: "++Fortnite+Release-7.40-CL-5046157-Windows",
        id: "Q8ph88FxJtDqcyJmvUaG6fHzDtjJZA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/Q8ph88FxJtDqcyJmvUaG6fHzDtjJZA.manifest",
        icon: "c1s7p.jpg",
        banner: "c1s7b.jfif",
      },
    ],
  },
  c1s8: {
    shortName: "c1s8",
    seasonName: "Season 8",
    icon: "c1s8p.jpg",
    banner: "c1s8b.png",
    manifests: [
      {
        name: "8.00-CL-5203069",
        version: "++Fortnite+Release-8.00-CL-5203069-Windows",
        id: "NG07wjIyXZIU9qkeTUK1F4TqJ4bmTQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/NG07wjIyXZIU9qkeTUK1F4TqJ4bmTQ.manifest",
        icon: "c1s8p.jpg",
        banner: "c1s8b.jfif",
      },
      {
        name: "8.20-CL-5625478",
        version: "++Fortnite+Release-8.20-CL-5625478-Windows",
        id: "x38m5mG7upd9og3yGE-ueFK_O6BIQw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/x38m5mG7upd9og3yGE-ueFK_O6BIQw.manifest",
        icon: "c1s8p.jpg",
        banner: "c1s8b.jfif",
      },
      {
        name: "8.30-CL-5793395",
        version: "++Fortnite+Release-8.30-CL-5793395-Windows",
        id: "AIwH4n9OxkItTP-mm0WaczfFJMvz3g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/AIwH4n9OxkItTP-mm0WaczfFJMvz3g.manifest",
        icon: "c1s8p.jpg",
        banner: "c1s8b.jfif",
      },
      {
        name: "8.40-CL-6005771",
        version: "++Fortnite+Release-8.40-CL-6005771-Windows",
        id: "s0i1dCn0kmzuWgbk90G0_cs8MN2qiw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/s0i1dCn0kmzuWgbk90G0_cs8MN2qiw.manifest",
        icon: "c1s8p.jpg",
        banner: "c1s8b.jfif",
      },
      {
        name: "8.50-CL-6058028",
        version: "++Fortnite+Release-8.50-CL-6058028-Windows",
        id: "7Om3eXVxOTO5r1vO-ES5AE-fKKwg1w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/7Om3eXVxOTO5r1vO-ES5AE-fKKwg1w.manifest",
        icon: "c1s8p.jpg",
        banner: "c1s8b.jfif",
      },
      {
        name: "8.51-CL-6165369",
        version: "++Fortnite+Release-8.51-CL-6165369-Windows",
        id: "21yEPkbqhNy_ePUECE6oTHEmg0SIfw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/21yEPkbqhNy_ePUECE6oTHEmg0SIfw.manifest",
        icon: "c1s8p.jpg",
        banner: "c1s8b.jfif",
      },
    ],
  },
  c1s9: {
    shortName: "c1s9",
    seasonName: "Season 9",
    icon: "c1s9p.jpg",
    banner: "c1s9b.png",
    manifests: [
      {
        name: "9.00-CL-6337466",
        version: "++Fortnite+Release-9.00-CL-6337466-Windows",
        id: "C3X86uPUO7rnPHrTG0S_sc8MXsPTFw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/C3X86uPUO7rnPHrTG0S_sc8MXsPTFw.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.01-CL-6428087",
        version: "++Fortnite+Release-9.01-CL-6428087-Windows",
        id: "4Sk9lFTsWh8D8G5bu0GAsFfJytlcMg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/4Sk9lFTsWh8D8G5bu0GAsFfJytlcMg.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.10-CL-6573057",
        version: "++Fortnite+Release-9.10-CL-6573057-Windows",
        id: "zPxI3f1ZAFSgFAMCZ0mjKySOC1AU5g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/zPxI3f1ZAFSgFAMCZ0mjKySOC1AU5g.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.10-CL-6616201",
        version: "++Fortnite+Release-9.10-CL-6616201-Windows",
        id: "bUVzbMy3cXw_TZ_nOUudQYTzqU8B0w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/bUVzbMy3cXw_TZ_nOUudQYTzqU8B0w.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.10-CL-6639283",
        version: "++Fortnite+Release-9.10-CL-6639283-Windows",
        id: "EwnvZ_rcCnmmOGRl9k6I2cKbZKpZog",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/EwnvZ_rcCnmmOGRl9k6I2cKbZKpZog.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.20-CL-6822798",
        version: "++Fortnite+Release-9.20-CL-6822798-Windows",
        id: "fomNLp5WNnJMCktOx0ehYYhXHjQ4PQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/fomNLp5WNnJMCktOx0ehYYhXHjQ4PQ.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.21-CL-6922310",
        version: "++Fortnite+Release-9.21-CL-6922310-Windows",
        id: "RWD-a5em9GzeNI9OK0aCgRMoxsaOIw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/RWD-a5em9GzeNI9OK0aCgRMoxsaOIw.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.30-CL-7021684",
        version: "++Fortnite+Release-9.30-CL-7021684-Windows",
        id: "Ny9N1fq0vOHr6Y6fhEyumZAfbiqCsA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/Ny9N1fq0vOHr6Y6fhEyumZAfbiqCsA.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.30-CL-7095426",
        version: "++Fortnite+Release-9.30-CL-7095426-Windows",
        id: "HrjjiaI8qjk0eZ76_Ey2bOwsoKgynw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/HrjjiaI8qjk0eZ76_Ey2bOwsoKgynw.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.40-CL-7315705",
        version: "++Fortnite+Release-9.40-CL-7315705-Windows",
        id: "BJqXmVW32yHN2EDJlkiwUn0CyZDm1g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/BJqXmVW32yHN2EDJlkiwUn0CyZDm1g.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.41-CL-7463579",
        version: "++Fortnite+Release-9.41-CL-7463579-Windows",
        id: "nVbZgzQG9HpntwQMmEm5ic1NLV_EeQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/nVbZgzQG9HpntwQMmEm5ic1NLV_EeQ.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
      {
        name: "9.41-CL-7609292",
        version: "++Fortnite+Release-9.41-CL-7609292-Windows",
        id: "XA1rr1l_FpmcNdkr7kG1CXRUNcX8lg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/XA1rr1l_FpmcNdkr7kG1CXRUNcX8lg.manifest",
        icon: "c1s9p.jpg",
        banner: "c1s9b.jfif",
      },
    ],
  },
  c1s10: {
    shortName: "c1s10",
    seasonName: "Season X",
    icon: "c1s10p.jpg",
    banner: "c1s10b.png",
    manifests: [
      {
        name: "10.0-CL-7658179",
        version: "++Fortnite+Release-10.0-CL-7658179-Windows",
        id: "wcfjh9c-okLtEOiDMkG8VzIC1p-ENg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/wcfjh9c-okLtEOiDMkG8VzIC1p-ENg.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.0-CL-7704164",
        version: "++Fortnite+Release-10.0-CL-7704164-Windows",
        id: "7C0cEaVSyWc6Fge6RE2N7IqJ4oPhww",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/7C0cEaVSyWc6Fge6RE2N7IqJ4oPhww.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.10-CL-7955722",
        version: "++Fortnite+Release-10.10-CL-7955722-Windows",
        id: "QpjVgBdS5NubVduhREqDPr8piZTw-w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/QpjVgBdS5NubVduhREqDPr8piZTw-w.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.20-CL-8243923",
        version: "++Fortnite+Release-10.20-CL-8243923-Windows",
        id: "_bbar1M1lP4jGq8rh0-aNNBuLtiykQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/_bbar1M1lP4jGq8rh0-aNNBuLtiykQ.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.20-CL-8360257",
        version: "++Fortnite+Release-10.20-CL-8360257-Windows",
        id: "VMzZoB9Jq0hTA6qusEm04UnAh6UKBA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/VMzZoB9Jq0hTA6qusEm04UnAh6UKBA.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.20-CL-8456527",
        version: "++Fortnite+Release-10.20-CL-8456527-Windows",
        id: "tzAOZKgKw-0aMGrTR0quWeW2a6OYmA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/tzAOZKgKw-0aMGrTR0quWeW2a6OYmA.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.30-CL-8569414",
        version: "++Fortnite+Release-10.30-CL-8569414-Windows",
        id: "9ZamWPoRkp27pBkCmEW67-k3ekT4ZQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/9ZamWPoRkp27pBkCmEW67-k3ekT4ZQ.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.31-CL-8723043",
        version: "++Fortnite+Release-10.31-CL-8723043-Windows",
        id: "DN-rIV_Kr52qz46BIkWDz1yk1fvR3A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/DN-rIV_Kr52qz46BIkWDz1yk1fvR3A.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.40-CL-8970213",
        version: "++Fortnite+Release-10.40-CL-8970213-Windows",
        id: "V4MspBnLrkKqBr8NAU2NeORA1Vj0bA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/V4MspBnLrkKqBr8NAU2NeORA1Vj0bA.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.40-CL-9302865",
        version: "++Fortnite+Release-10.40-CL-9302865-Windows",
        id: "wOtgyHQea154yQ0EfUqZDhS6yTqsig",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/wOtgyHQea154yQ0EfUqZDhS6yTqsig.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
      {
        name: "10.40-CL-9380822",
        version: "++Fortnite+Release-10.40-CL-9380822-Windows",
        id: "8B9_KlR_rT7EAYpOQ0-Z_6gvsOS2yQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/8B9_KlR_rT7EAYpOQ0-Z_6gvsOS2yQ.manifest",
        icon: "c1s10p.jpg",
        banner: "c1s10b.jfif",
      },
    ],
  },
  c2s1: {
    shortName: "c2s1",
    seasonName: "Chapter 2, Season 1",
    icon: "c2s1p.png",
    banner: "c2s1b.png",
    manifests: [
      {
        name: "11.00-CL-9562734",
        version: "++Fortnite+Release-11.00-CL-9562734-Windows",
        id: "5-0v4B3kpK4XpRczak2Pc7dtlqah1A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/5-0v4B3kpK4XpRczak2Pc7dtlqah1A.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.00-CL-9603448",
        version: "++Fortnite+Release-11.00-CL-9603448-Windows",
        id: "sMeK9k1aLob5LB-hoUKKLmUfxwC-1Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/sMeK9k1aLob5LB-hoUKKLmUfxwC-1Q.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.01-CL-9728272",
        version: "++Fortnite+Release-11.01-CL-9728272-Windows",
        id: "QZRwNP2PFJA8ZRaJf0CvTdp_lifayg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/QZRwNP2PFJA8ZRaJf0CvTdp_lifayg.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.10-CL-9844520",
        version: "++Fortnite+Release-11.10-CL-9844520-Windows",
        id: "4Qd63MleE2D9iPwREU2lELyJc--PFA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/4Qd63MleE2D9iPwREU2lELyJc--PFA.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.10-CL-9901083",
        version: "++Fortnite+Release-11.10-CL-9901083-Windows",
        id: "4uiD_B-WF9I5W4h1M0m11f7iQ8zu6g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/4uiD_B-WF9I5W4h1M0m11f7iQ8zu6g.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.11-CL-10082788",
        version: "++Fortnite+Release-11.11-CL-10082788-Windows",
        id: "iVPwyvOxVsK6klhS1UeSRfQfJbPGZA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/iVPwyvOxVsK6klhS1UeSRfQfJbPGZA.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.20-CL-10297577",
        version: "++Fortnite+Release-11.20-CL-10297577-Windows",
        id: "nx1sa8DEmaw-9_I8YEiMZ50FaDr0AQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/nx1sa8DEmaw-9_I8YEiMZ50FaDr0AQ.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.20-CL-10328358",
        version: "++Fortnite+Release-11.20-CL-10328358-Windows",
        id: "WmJlwXvlu0LMLVGGqUmXPy93OQSFBw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/WmJlwXvlu0LMLVGGqUmXPy93OQSFBw.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.21-CL-10481509",
        version: "++Fortnite+Release-11.21-CL-10481509-Windows",
        id: "fKa-ZiFTzVP69JIxIky1OfZ0KPZnMQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/fKa-ZiFTzVP69JIxIky1OfZ0KPZnMQ.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.30-CL-10639804",
        version: "++Fortnite+Release-11.30-CL-10639804-Windows",
        id: "b26Zho3UFXcmjFwIy0G8T4x3tbX1yA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/b26Zho3UFXcmjFwIy0G8T4x3tbX1yA.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.30-CL-10708866",
        version: "++Fortnite+Release-11.30-CL-10708866-Windows",
        id: "DDQp02DHMVKums1CD0a5qa-GxxTxJg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/DDQp02DHMVKums1CD0a5qa-GxxTxJg.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.31-CL-10760473",
        version: "++Fortnite+Release-11.31-CL-10760473-Windows",
        id: "Dp8ZQlhdJ9tyQRRMGkO3gpZgQMGZmw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/Dp8ZQlhdJ9tyQRRMGkO3gpZgQMGZmw.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.31-CL-10795579",
        version: "++Fortnite+Release-11.31-CL-10795579-Windows",
        id: "M6XhmsGG8zV2O9EOkkqfKOfb9CBNeA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/M6XhmsGG8zV2O9EOkkqfKOfb9CBNeA.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.31-CL-10800459",
        version: "++Fortnite+Release-11.31-CL-10800459-Windows",
        id: "I9bgKLDRd2f-FvbbCkiyhu_u2eczYg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/I9bgKLDRd2f-FvbbCkiyhu_u2eczYg.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.40-CL-10951104",
        version: "++Fortnite+Release-11.40-CL-10951104-Windows",
        id: "gWTicfkWyAH3_8fpQEixmSUn0qhcSA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/gWTicfkWyAH3_8fpQEixmSUn0qhcSA.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.40-CL-11039906",
        version: "++Fortnite+Release-11.40-CL-11039906-Windows",
        id: "jpzvVty5Z5mmS0h9y0O72YRP0hTjFA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/jpzvVty5Z5mmS0h9y0O72YRP0hTjFA.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.40-CL-11109625",
        version: "++Fortnite+Release-11.40-CL-11109625-Windows",
        id: "MErWwWjI-gmQmpwUCE-smeOIJY_L-A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/MErWwWjI-gmQmpwUCE-smeOIJY_L-A.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.50-CL-11204868",
        version: "++Fortnite+Release-11.50-CL-11204868-Windows",
        id: "skWUaAJHBVlghBWDmku50A2BNtOJ1Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/skWUaAJHBVlghBWDmku50A2BNtOJ1Q.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
      {
        name: "11.50-CL-11265652",
        version: "++Fortnite+Release-11.50-CL-11265652-Windows",
        id: "o8omInZNucJoBbOSh0iU2JCJW5aV9w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/o8omInZNucJoBbOSh0iU2JCJW5aV9w.manifest",
        icon: "c2s1p.png",
        banner: "c2s1b.jfif",
      },
    ],
  },
  c2s2: {
    shortName: "c2s2",
    seasonName: "Chapter 2, Season 2",
    icon: "c2s2p.jpg",
    banner: "c2s2b.png",
    manifests: [
      {
        name: "12.00-CL-11556442",
        version: "++Fortnite+Release-12.00-CL-11556442-Windows",
        id: "dLIo12SBCCJ13prtkEux9bq75peaaA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/dLIo12SBCCJ13prtkEux9bq75peaaA.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.00-CL-11566760",
        version: "++Fortnite+Release-12.00-CL-11566760-Windows",
        id: "zQVuaHVgKVM7M0lDNUapSOMstSi93w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/zQVuaHVgKVM7M0lDNUapSOMstSi93w.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.00-CL-11586896",
        version: "++Fortnite+Release-12.00-CL-11586896-Windows",
        id: "WG_A20YyTgZJqtTAikSFdl0DmX4pHw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/WG_A20YyTgZJqtTAikSFdl0DmX4pHw.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.10-CL-11794982",
        version: "++Fortnite+Release-12.10-CL-11794982-Windows",
        id: "OZ1A766vl6Uj_Nf-C02US-sgDesERw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/OZ1A766vl6Uj_Nf-C02US-sgDesERw.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.10-CL-11883027",
        version: "++Fortnite+Release-12.10-CL-11883027-Windows",
        id: "19R3rvzj1VXoJVLUlEyfNTi0HPeztQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/19R3rvzj1VXoJVLUlEyfNTi0HPeztQ.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.20-CL-12170032",
        version: "++Fortnite+Release-12.20-CL-12170032-Windows",
        id: "SkZEU_IJTiW1z-hvyUCQY4AonuHmJQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/SkZEU_IJTiW1z-hvyUCQY4AonuHmJQ.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.20-CL-12236980",
        version: "++Fortnite+Release-12.20-CL-12236980-Windows",
        id: "mVCAttTZSI3CLUbvdEmn1Yu08271-w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/mVCAttTZSI3CLUbvdEmn1Yu08271-w.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.21-CL-12353830",
        version: "++Fortnite+Release-12.21-CL-12353830-Windows",
        id: "9_K5hT-t-j1KPiPCXkCzWNSsvzDRTw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/9_K5hT-t-j1KPiPCXkCzWNSsvzDRTw.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.30-CL-12493283",
        version: "++Fortnite+Release-12.30-CL-12493283-Windows",
        id: "X-9EArNutqedIqnak0u3fARhNtBvYg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/X-9EArNutqedIqnak0u3fARhNtBvYg.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.30-CL-12624643",
        version: "++Fortnite+Release-12.30-CL-12624643-Windows",
        id: "4lcktXU--gKJ8XJo3EGtkKzNBGyGdQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/4lcktXU--gKJ8XJo3EGtkKzNBGyGdQ.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.40-CL-12837456",
        version: "++Fortnite+Release-12.40-CL-12837456-Windows",
        id: "d_Or-l0fAsszcitXgE-_9nI4-TANLg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/d_Or-l0fAsszcitXgE-_9nI4-TANLg.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.41-CL-12905909",
        version: "++Fortnite+Release-12.41-CL-12905909-Windows",
        id: "jTfg_xZZ2H4T9L__PEmzI2Y90hr9Aw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/jTfg_xZZ2H4T9L__PEmzI2Y90hr9Aw.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.50-CL-13044369",
        version: "++Fortnite+Release-12.50-CL-13044369-Windows",
        id: "WFWEb9HuFddgR84jm0SHQAzLSw6u2g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/WFWEb9HuFddgR84jm0SHQAzLSw6u2g.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.50-CL-13137020",
        version: "++Fortnite+Release-12.50-CL-13137020-Windows",
        id: "gVGThRYKo0MZpIko_0mWf6b0MBCleA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/gVGThRYKo0MZpIko_0mWf6b0MBCleA.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.50-CL-13193885",
        version: "++Fortnite+Release-12.50-CL-13193885-Windows",
        id: "Hz6B_sHg1yMiMfG5uUq93flJAlosuw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/Hz6B_sHg1yMiMfG5uUq93flJAlosuw.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.60-CL-13315662",
        version: "++Fortnite+Release-12.60-CL-13315662-Windows",
        id: "KVqZ_bGv9_ZjYaRWn0SwSEizJyeJiQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/KVqZ_bGv9_ZjYaRWn0SwSEizJyeJiQ.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.60-CL-13477524",
        version: "++Fortnite+Release-12.60-CL-13477524-Windows",
        id: "FgKMa-wCOesX6Abl1kifJYcLTuJ-5A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/FgKMa-wCOesX6Abl1kifJYcLTuJ-5A.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
      {
        name: "12.61-CL-13498980",
        version: "++Fortnite+Release-12.61-CL-13498980-Windows",
        id: "kpWEntSL0uNcIcH4ZUm6nFsFnar-3w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/kpWEntSL0uNcIcH4ZUm6nFsFnar-3w.manifest",
        icon: "c2s2p.jpg",
        banner: "c2s2b.jfif",
      },
    ],
  },
  c2s3: {
    shortName: "c2s3",
    seasonName: "Chapter 2, Season 3",
    icon: "c2s3p.jpg",
    banner: "c2s3b.png",
    manifests: [
      {
        name: "13.00-CL-13649278",
        version: "++Fortnite+Release-13.00-CL-13649278-Windows",
        id: "ZUQyNUHswApJSCYuokeA-Q7j60nFHg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/ZUQyNUHswApJSCYuokeA-Q7j60nFHg.manifest",
        icon: "c2s3p.jpg",
        banner: "c2s3b.jfif",
      },
      {
        name: "13.00-CL-13696059",
        version: "++Fortnite+Release-13.00-CL-13696059-Windows",
        id: "6w63WNDQ6fnOhOZ3SE-vegG_R-EQlg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/6w63WNDQ6fnOhOZ3SE-vegG_R-EQlg.manifest",
        icon: "c2s3p.jpg",
        banner: "c2s3b.jfif",
      },
      {
        name: "13.00-CL-13715544",
        version: "++Fortnite+Release-13.00-CL-13715544-Windows",
        id: "-HHPY5se-mwf2BiOLkSRJvaCWDUKnA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/-HHPY5se-mwf2BiOLkSRJvaCWDUKnA.manifest",
        icon: "c2s3p.jpg",
        banner: "c2s3b.jfif",
      },
      {
        name: "13.20-CL-13777676",
        version: "++Fortnite+Release-13.20-CL-13777676-Windows",
        id: "zOUaEMjHOjnoHT50tEmEUqeJAT7mLA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/zOUaEMjHOjnoHT50tEmEUqeJAT7mLA.manifest",
        icon: "c2s3p.jpg",
        banner: "c2s3b.jfif",
      },
      {
        name: "13.30-CL-13884634",
        version: "++Fortnite+Release-13.30-CL-13884634-Windows",
        id: "__d-73Y9siJhxSaCRE6egZe3gbpjNw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/__d-73Y9siJhxSaCRE6egZe3gbpjNw.manifest",
        icon: "c2s3p.jpg",
        banner: "c2s3b.jfif",
      },
      {
        name: "13.40-CL-14008768",
        version: "++Fortnite+Release-13.40-CL-14008768-Windows",
        id: "r70n58nGmOBda57S_EST7qGOsLgPTw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/r70n58nGmOBda57S_EST7qGOsLgPTw.manifest",
        icon: "c2s3p.jpg",
        banner: "c2s3b.jfif",
      },
      {
        name: "13.40-CL-14036559",
        version: "++Fortnite+Release-13.40-CL-14036559-Windows",
        id: "lxP7nVJQuqONDOBmy0eOuS3UycHqKA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/lxP7nVJQuqONDOBmy0eOuS3UycHqKA.manifest",
        icon: "c2s3p.jpg",
        banner: "c2s3b.jfif",
      },
      {
        name: "13.40-CL-14113327",
        version: "++Fortnite+Release-13.40-CL-14113327-Windows",
        id: "k39Q5tXfdlFV3Vi8tEWwdzJstOCncw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/k39Q5tXfdlFV3Vi8tEWwdzJstOCncw.manifest",
        icon: "c2s3p.jpg",
        banner: "c2s3b.jfif",
      },
    ],
  },
  c2s4: {
    shortName: "c2s4",
    seasonName: "Chapter 2, Season 4",
    icon: "c2s4p.jpg",
    banner: "c2s4b.png",
    manifests: [
      {
        name: "14.00-CL-14173417",
        version: "++Fortnite+Release-14.00-CL-14173417-Windows",
        id: "WIYuFdTOCn_b67Mnik-Q0teZEIWd-Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/WIYuFdTOCn_b67Mnik-Q0teZEIWd-Q.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.00-CL-14199892",
        version: "++Fortnite+Release-14.00-CL-14199892-Windows",
        id: "-IAv9taY4Yjn2jw5xU2l_BgrdMs8PQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/-IAv9taY4Yjn2jw5xU2l_BgrdMs8PQ.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.00-CL-14211474",
        version: "++Fortnite+Release-14.00-CL-14211474-Windows",
        id: "eV3odPpOFO5KqwyQaUqN6BRpXUIV1Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/eV3odPpOFO5KqwyQaUqN6BRpXUIV1Q.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.10-CL-14276912",
        version: "++Fortnite+Release-14.10-CL-14276912-Windows",
        id: "HhLsZiMFk17s3fY5i0OSBOI8MtsFdA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/HhLsZiMFk17s3fY5i0OSBOI8MtsFdA.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.10-CL-14288110",
        version: "++Fortnite+Release-14.10-CL-14288110-Windows",
        id: "A5rhLa8WYtEHXXDBu0qY6QjeYRAZBA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/A5rhLa8WYtEHXXDBu0qY6QjeYRAZBA.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.10-CL-14312695",
        version: "++Fortnite+Release-14.10-CL-14312695-Windows",
        id: "iOp7OXIvJZsHpe1X6UavQXOryv-3dg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/iOp7OXIvJZsHpe1X6UavQXOryv-3dg.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.20-CL-14354056",
        version: "++Fortnite+Release-14.20-CL-14354056-Windows",
        id: "3EjPigM-G_w7AHCIrUyLHu8t4KWtUA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/3EjPigM-G_w7AHCIrUyLHu8t4KWtUA.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.20-CL-14375974",
        version: "++Fortnite+Release-14.20-CL-14375974-Windows",
        id: "cbEscV3_fQIaHll8QEyadlm1u45o5g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/cbEscV3_fQIaHll8QEyadlm1u45o5g.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.20-CL-14384759",
        version: "++Fortnite+Release-14.20-CL-14384759-Windows",
        id: "08opnel1yrNVPmiQFkGQw7aDSvgUKg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/08opnel1yrNVPmiQFkGQw7aDSvgUKg.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.30-CL-14456520",
        version: "++Fortnite+Release-14.30-CL-14456520-Windows",
        id: "vSRBaHxfB_kuksWOEk2_PfUPG22MVw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/vSRBaHxfB_kuksWOEk2_PfUPG22MVw.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.40-CL-14512399",
        version: "++Fortnite+Release-14.40-CL-14512399-Windows",
        id: "BQ1lc_hzhBmmkfMkv0i-kBwqATdi0w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/BQ1lc_hzhBmmkfMkv0i-kBwqATdi0w.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.40-CL-14550713",
        version: "++Fortnite+Release-14.40-CL-14550713-Windows",
        id: "DClI318w-7eAMz2fmUuHgSkAlomU6g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/DClI318w-7eAMz2fmUuHgSkAlomU6g.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.50-CL-14617811",
        version: "++Fortnite+Release-14.50-CL-14617811-Windows",
        id: "TeUEJvLhEenUjW_LzEqFQuARF-vgoQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/TeUEJvLhEenUjW_LzEqFQuARF-vgoQ.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.50-CL-14643651",
        version: "++Fortnite+Release-14.50-CL-14643651-Windows",
        id: "iy2C4VZCKwMe83dKd0KofFbo8RcXmQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/iy2C4VZCKwMe83dKd0KofFbo8RcXmQ.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.60-CL-14756138",
        version: "++Fortnite+Release-14.60-CL-14756138-Windows",
        id: "eTVXl5pN2ru94uvYIkGIwgecMM0m_g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/eTVXl5pN2ru94uvYIkGIwgecMM0m_g.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.60-CL-14785135",
        version: "++Fortnite+Release-14.60-CL-14785135-Windows",
        id: "J7nUADncwk2szmTXwE-6Apsbr0ChGg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/J7nUADncwk2szmTXwE-6Apsbr0ChGg.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
      {
        name: "14.60-CL-14786821",
        version: "++Fortnite+Release-14.60-CL-14786821-Windows",
        id: "0zBnTzhzHTTQw-bMo06bpGonsWK9AA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/0zBnTzhzHTTQw-bMo06bpGonsWK9AA.manifest",
        icon: "c2s4p.jpg",
        banner: "c2s4b.jfif",
      },
    ],
  },
  c2s5: {
    shortName: "c2s5",
    seasonName: "Chapter 2, Season 5",
    icon: "c2s5p.jpg",
    banner: "c2s5b.png",
    manifests: [
      {
        name: "15.00-CL-14826719",
        version: "++Fortnite+Release-15.00-CL-14826719-Windows",
        id: "hEC9dL7-jjhVjaT9Ek6g5kPNmfx_oA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/hEC9dL7-jjhVjaT9Ek6g5kPNmfx_oA.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.00-CL-14835335",
        version: "++Fortnite+Release-15.00-CL-14835335-Windows",
        id: "pxgus3IjKexjBYe8O0qy6lPWTTBxOg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/pxgus3IjKexjBYe8O0qy6lPWTTBxOg.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.10-CL-14904303",
        version: "++Fortnite+Release-15.10-CL-14904303-Windows",
        id: "BW4Td1PSNWngBf-BQEO9orJjii-kyw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/BW4Td1PSNWngBf-BQEO9orJjii-kyw.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.10-CL-14937640",
        version: "++Fortnite+Release-15.10-CL-14937640-Windows",
        id: "g0WsAHmkYXL2MsV-lECsXK2PGKZOAQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/g0WsAHmkYXL2MsV-lECsXK2PGKZOAQ.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.10-CL-15014719",
        version: "++Fortnite+Release-15.10-CL-15014719-Windows",
        id: "gFzfWbu3uGpAQMxlskKxadJKCcOafA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/gFzfWbu3uGpAQMxlskKxadJKCcOafA.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.20-CL-15033494",
        version: "++Fortnite+Release-15.20-CL-15033494-Windows",
        id: "-oaPq13DQ1T7VAH3tUGxunSLza2Xdg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/-oaPq13DQ1T7VAH3tUGxunSLza2Xdg.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.20-CL-15070882",
        version: "++Fortnite+Release-15.20-CL-15070882-Windows",
        id: "ZC0C_kRQmlplPnuYMEursbDWqdT4XQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/ZC0C_kRQmlplPnuYMEursbDWqdT4XQ.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.21-CL-15083856",
        version: "++Fortnite+Release-15.21-CL-15083856-Windows",
        id: "PHWYNb_1EXWoIgq2JkuOABaZKZ2uAQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/PHWYNb_1EXWoIgq2JkuOABaZKZ2uAQ.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.30-CL-15233634",
        version: "++Fortnite+Release-15.30-CL-15233634-Windows",
        id: "4f_fOfqIHIMBff3XsUC2wdIZNvfgQg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/4f_fOfqIHIMBff3XsUC2wdIZNvfgQg.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.30-CL-15316852",
        version: "++Fortnite+Release-15.30-CL-15316852-Windows",
        id: "ejVcIMPTubEZ8oT6uU6eVNk43YKPvw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/ejVcIMPTubEZ8oT6uU6eVNk43YKPvw.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.30-CL-15341163",
        version: "++Fortnite+Release-15.30-CL-15341163-Windows",
        id: "x1dAKmBiMCwiWxbrt0yOzckFfitG8g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/x1dAKmBiMCwiWxbrt0yOzckFfitG8g.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.40-CL-15385160",
        version: "++Fortnite+Release-15.40-CL-15385160-Windows",
        id: "M-uL6hJU0HVPJLI2lUiqtQQsA7VYkg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/M-uL6hJU0HVPJLI2lUiqtQQsA7VYkg.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.40-CL-15419568",
        version: "++Fortnite+Release-15.40-CL-15419568-Windows",
        id: "u4MEHBVOxXYICGW680mzbo3QSEu58Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/u4MEHBVOxXYICGW680mzbo3QSEu58Q.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.40-CL-15424013",
        version: "++Fortnite+Release-15.40-CL-15424013-Windows",
        id: "tXOCpnf2iyNxmTGA0UqZ7NpEB08xmQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/tXOCpnf2iyNxmTGA0UqZ7NpEB08xmQ.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.40-CL-15496915",
        version: "++Fortnite+Release-15.40-CL-15496915-Windows",
        id: "NgICIOEJN6SUFYK6X0atmFurBtw_kQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/NgICIOEJN6SUFYK6X0atmFurBtw_kQ.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.50-CL-15526472",
        version: "++Fortnite+Release-15.50-CL-15526472-Windows",
        id: "vJW5mNtj-KyKaUo26E2UeuDBXtgUNQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/vJW5mNtj-KyKaUo26E2UeuDBXtgUNQ.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
      {
        name: "15.50-CL-15570449",
        version: "++Fortnite+Release-15.50-CL-15570449-Windows",
        id: "N4qaUfEGF1WRgxFYSEK0dCyF-9DLfg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/N4qaUfEGF1WRgxFYSEK0dCyF-9DLfg.manifest",
        icon: "c2s5p.jpg",
        banner: "c2s5b.jfif",
      },
    ],
  },
  c2s6: {
    shortName: "c2s6",
    seasonName: "Chapter 2, Season 6",
    icon: "c2s6p.jpg",
    banner: "c2s6b.png",
    manifests: [
      {
        name: "16.00-CL-15685441",
        version: "++Fortnite+Release-16.00-CL-15685441-Windows",
        id: "0TUjehLQVK8zW6tqWkquGEm4QAE0xg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/0TUjehLQVK8zW6tqWkquGEm4QAE0xg.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.00-CL-15713390",
        version: "++Fortnite+Release-16.00-CL-15713390-Windows",
        id: "2N-wx7hYkt8Ni7lBDkausAkNOmtdoA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/2N-wx7hYkt8Ni7lBDkausAkNOmtdoA.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.00-CL-15727376",
        version: "++Fortnite+Release-16.00-CL-15727376-Windows",
        id: "sjtPnOPJGVjpCn_MeU62f4dUQqSe4g",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/sjtPnOPJGVjpCn_MeU62f4dUQqSe4g.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.10-CL-15851811",
        version: "++Fortnite+Release-16.10-CL-15851811-Windows",
        id: "L9rTqg1OLlwprMBpdUaiNYI4-yUc5Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/L9rTqg1OLlwprMBpdUaiNYI4-yUc5Q.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.10-CL-15862581",
        version: "++Fortnite+Release-16.10-CL-15862581-Windows",
        id: "CIwICRP-E1flI4b-XUWFsQdska-RbQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/CIwICRP-E1flI4b-XUWFsQdska-RbQ.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.10-CL-15883297",
        version: "++Fortnite+Release-16.10-CL-15883297-Windows",
        id: "-rvrkgHU7oWbYnwuPES1P2BfFi7QMQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/-rvrkgHU7oWbYnwuPES1P2BfFi7QMQ.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.10-CL-15898731",
        version: "++Fortnite+Release-16.10-CL-15898731-Windows",
        id: "RIbiJD1siAR2cVG_wUuKp5lPxnvCkw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/RIbiJD1siAR2cVG_wUuKp5lPxnvCkw.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.10-CL-15913292",
        version: "++Fortnite+Release-16.10-CL-15913292-Windows",
        id: "Twf_6XRPiaDIGrA6ckiSmI1V6FqxSQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/Twf_6XRPiaDIGrA6ckiSmI1V6FqxSQ.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.20-CL-15961073",
        version: "++Fortnite+Release-16.20-CL-15961073-Windows",
        id: "45Yu75CiPHkk0EzIj0WBYuF9VW19zA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/45Yu75CiPHkk0EzIj0WBYuF9VW19zA.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.20-CL-15987165",
        version: "++Fortnite+Release-16.20-CL-15987165-Windows",
        id: "p60cPJmW8tjdLQbgWkqIlst_ZBXYkA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/p60cPJmW8tjdLQbgWkqIlst_ZBXYkA.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.20-CL-15998392",
        version: "++Fortnite+Release-16.20-CL-15998392-Windows",
        id: "-DzHROu43oWjoqUbwkqtK2BcyusIJg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/-DzHROu43oWjoqUbwkqtK2BcyusIJg.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.20-CL-16042441",
        version: "++Fortnite+Release-16.20-CL-16042441-Windows",
        id: "ob4MNq3vl1K4IlNrQkmMRHKGXHri0Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/ob4MNq3vl1K4IlNrQkmMRHKGXHri0Q.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.30-CL-16086208",
        version: "++Fortnite+Release-16.30-CL-16086208-Windows",
        id: "OzKzsnONyKV98T6gPU-kYL2m23VpgQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/OzKzsnONyKV98T6gPU-kYL2m23VpgQ.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.30-CL-16163563",
        version: "++Fortnite+Release-16.30-CL-16163563-Windows",
        id: "mnQTrr-mpTUTiv5Ab0qsYu_TrsLYzA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/mnQTrr-mpTUTiv5Ab0qsYu_TrsLYzA.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.40-CL-16218553",
        version: "++Fortnite+Release-16.40-CL-16218553-Windows",
        id: "PlBdWqpuSh7V8Uc_yUG5gX8HFLPwag",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/PlBdWqpuSh7V8Uc_yUG5gX8HFLPwag.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.50-CL-16432754",
        version: "++Fortnite+Release-16.50-CL-16432754-Windows",
        id: "myacVPh3VDv1zXI4Z0OpAVE76zqoiQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/myacVPh3VDv1zXI4Z0OpAVE76zqoiQ.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
      {
        name: "16.50-CL-16469788",
        version: "++Fortnite+Release-16.50-CL-16469788-Windows",
        id: "JoLlB3IhtR6FpOfjYEuCkElNi5yxOA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/JoLlB3IhtR6FpOfjYEuCkElNi5yxOA.manifest",
        icon: "c2s6p.jpg",
        banner: "c2s6b.jfif",
      },
    ],
  },
  c2s7: {
    shortName: "c2s7",
    seasonName: "Chapter 2, Season 7",
    icon: "c2s7p.jpg",
    banner: "c2s7b.png",
    manifests: [
      {
        name: "17.00-CL-16555138",
        version: "++Fortnite+Release-17.00-CL-16555138-Windows",
        id: "r01_i6Vdba86jyg6K0mmOLfNO_rmAw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/r01_i6Vdba86jyg6K0mmOLfNO_rmAw.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.00-CL-16593740",
        version: "++Fortnite+Release-17.00-CL-16593740-Windows",
        id: "nowzVL6UKD9nC3vhPEuIX1kZWIez0Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/nowzVL6UKD9nC3vhPEuIX1kZWIez0Q.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.10-CL-16701187",
        version: "++Fortnite+Release-17.10-CL-16701187-Windows",
        id: "rv6Abzcql-WLokq8PEOGZF7jXTcBOw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/rv6Abzcql-WLokq8PEOGZF7jXTcBOw.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.10-CL-16745144",
        version: "++Fortnite+Release-17.10-CL-16745144-Windows",
        id: "SCNv_xqyQm1ABpj-T0-sMEjXmbiRHQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/SCNv_xqyQm1ABpj-T0-sMEjXmbiRHQ.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.20-CL-16868155",
        version: "++Fortnite+Release-17.20-CL-16868155-Windows",
        id: "YBHDg0lcr9LtodRbfUeKzV7rGyt2QA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/YBHDg0lcr9LtodRbfUeKzV7rGyt2QA.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.21-CL-16949556",
        version: "++Fortnite+Release-17.21-CL-16949556-Windows",
        id: "hyS6T7m1z-V4PCkngEe4SvuqSEzrHQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/hyS6T7m1z-V4PCkngEe4SvuqSEzrHQ.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.21-CL-16967001",
        version: "++Fortnite+Release-17.21-CL-16967001-Windows",
        id: "FTvF_Dz-EmynfOkGiE-OMdvqTWKa2Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/FTvF_Dz-EmynfOkGiE-OMdvqTWKa2Q.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.30-CL-17004569",
        version: "++Fortnite+Release-17.30-CL-17004569-Windows",
        id: "iv2x3ijMayy7Mynn20ygKCjg5W1j_w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/iv2x3ijMayy7Mynn20ygKCjg5W1j_w.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.40-CL-17162853",
        version: "++Fortnite+Release-17.40-CL-17162853-Windows",
        id: "fcwYvaMl7pSHfGB-fkmsiSRMqmHUtw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/fcwYvaMl7pSHfGB-fkmsiSRMqmHUtw.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.40-CL-17215766",
        version: "++Fortnite+Release-17.40-CL-17215766-Windows",
        id: "rTR-Nb3LTmsCkWfeDEmXnKyETh1kow",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/rTR-Nb3LTmsCkWfeDEmXnKyETh1kow.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.40-CL-17269705",
        version: "++Fortnite+Release-17.40-CL-17269705-Windows",
        id: "dLQOoiwtjYOwEaMOHkazSPcbOun7Zg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/dLQOoiwtjYOwEaMOHkazSPcbOun7Zg.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
      {
        name: "17.50-CL-17388565",
        version: "++Fortnite+Release-17.50-CL-17388565-Windows",
        id: "hbkx_qhpofyAGF3VQUaU-0ke3WwKBg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/hbkx_qhpofyAGF3VQUaU-0ke3WwKBg.manifest",
        icon: "c2s7p.jpg",
        banner: "c2s7b.jfif",
      },
    ],
  },
  c2s8: {
    shortName: "c2s8",
    seasonName: "Chapter 2, Season 8",
    icon: "c2s8p.jpg",
    banner: "c2s8b.png",
    manifests: [
      {
        name: "18.00-CL-17519952",
        version: "++Fortnite+Release-18.00-CL-17519952-Windows",
        id: "j8Xdl9aEhZ-WkNenIUywKT0MrOAoxA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/j8Xdl9aEhZ-WkNenIUywKT0MrOAoxA.manifest",
        icon: "c2s8p.jpg",
        banner: "c2s8b.jfif",
      },
      {
        name: "18.10-CL-17619277",
        version: "++Fortnite+Release-18.10-CL-17619277-Windows",
        id: "5aOpBhE4Ru3-v2YFzUSGGuWGdEzyXQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/5aOpBhE4Ru3-v2YFzUSGGuWGdEzyXQ.manifest",
        icon: "c2s8p.jpg",
        banner: "c2s8b.jfif",
      },
      {
        name: "18.10-CL-17661844",
        version: "++Fortnite+Release-18.10-CL-17661844-Windows",
        id: "hu7N3s__H28na2Oro06-draLSCt5UQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/hu7N3s__H28na2Oro06-draLSCt5UQ.manifest",
        icon: "c2s8p.jpg",
        banner: "c2s8b.jfif",
      },
      {
        name: "18.20-CL-17745267",
        version: "++Fortnite+Release-18.20-CL-17745267-Windows",
        id: "NVDpDsRkObzIXej9LkeokHUwMj2B_A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/NVDpDsRkObzIXej9LkeokHUwMj2B_A.manifest",
        icon: "c2s8p.jpg",
        banner: "c2s8b.jfif",
      },
      {
        name: "18.21-CL-17811397",
        version: "++Fortnite+Release-18.21-CL-17811397-Windows",
        id: "OW-ufOH2A5Ofv8BdZkqkK7BdOh5_lg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/OW-ufOH2A5Ofv8BdZkqkK7BdOh5_lg.manifest",
        icon: "c2s8p.jpg",
        banner: "c2s8b.jfif",
      },
      {
        name: "18.30-CL-17882303",
        version: "++Fortnite+Release-18.30-CL-17882303-Windows",
        id: "qtQkupWgkRT0VojLbEyVUX_v2CJsPA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/qtQkupWgkRT0VojLbEyVUX_v2CJsPA.manifest",
        icon: "c2s8p.jpg",
        banner: "c2s8b.jfif",
      },
      {
        name: "18.40-CL-18163738",
        version: "++Fortnite+Release-18.40-CL-18163738-Windows",
        id: "BIZ9URud-wgSnyLid0OGLukI37r96A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/BIZ9URud-wgSnyLid0OGLukI37r96A.manifest",
        icon: "c2s8p.jpg",
        banner: "c2s8b.jfif",
      },
    ],
  },
  c3s1: {
    shortName: "c3s1",
    seasonName: "Chapter 3, Season 1",
    icon: "c3s1p.jpg",
    banner: "c3s1b.png",
    manifests: [
      {
        name: "19.00-CL-18335626",
        version: "++Fortnite+Release-19.00-CL-18335626-Windows",
        id: "3jmxoAS1Tgz9gq7E-0aS-x8K-VGl-Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/3jmxoAS1Tgz9gq7E-0aS-x8K-VGl-Q.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
      {
        name: "19.00-CL-18380290",
        version: "++Fortnite+Release-19.00-CL-18380290-Windows",
        id: "cNHihchpitbEYAXS-EKrV5kp-IZt3A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/cNHihchpitbEYAXS-EKrV5kp-IZt3A.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
      {
        name: "19.01-CL-18415863",
        version: "++Fortnite+Release-19.01-CL-18415863-Windows",
        id: "qU41bqg7uhIaWfNN40-Fp093MSdhBQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/qU41bqg7uhIaWfNN40-Fp093MSdhBQ.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
      {
        name: "19.01-CL-18489740",
        version: "++Fortnite+Release-19.01-CL-18489740-Windows",
        id: "sr6SWap2l2Th30T0yEu2Ux55PgJiJg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/sr6SWap2l2Th30T0yEu2Ux55PgJiJg.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
      {
        name: "19.10-CL-18675304",
        version: "++Fortnite+Release-19.10-CL-18675304-Windows",
        id: "1NvzUq3kqI4tf6gUB0uPlpO5p3KA-A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/1NvzUq3kqI4tf6gUB0uPlpO5p3KA-A.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
      {
        name: "19.20-CL-18775446",
        version: "++Fortnite+Release-19.20-CL-18775446-Windows",
        id: "QmlSaeGwrvA00GMFGkaC0jV6zRe-Sw",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/QmlSaeGwrvA00GMFGkaC0jV6zRe-Sw.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
      {
        name: "19.30-CL-18948597",
        version: "++Fortnite+Release-19.30-CL-18948597-Windows",
        id: "sFI_6cQceiw9r_ygt0u2ByaSfqpOdA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/sFI_6cQceiw9r_ygt0u2ByaSfqpOdA.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
      {
        name: "19.30-CL-19027703",
        version: "++Fortnite+Release-19.30-CL-19027703-Windows",
        id: "_VitLSYEQWEEAA7bLUCchjzkBQZ49A",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/_VitLSYEQWEEAA7bLUCchjzkBQZ49A.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
      {
        name: "19.40-CL-19215531",
        version: "++Fortnite+Release-19.40-CL-19215531-Windows",
        id: "gbEURBYqoXFtBOGD_kqR3AaHo8H_og",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/gbEURBYqoXFtBOGD_kqR3AaHo8H_og.manifest",
        icon: "c3s1p.jpg",
        banner: "c3s1b.jfif",
      },
    ],
  },
  c3s2: {
    shortName: "c3s2",
    seasonName: "Chapter 3, Season 2",
    icon: "c3s2p.jpg",
    banner: "c3s2b.png",
    manifests: [
      {
        name: "20.00-CL-19458861",
        version: "++Fortnite+Release-20.00-CL-19458861-Windows",
        id: "iO3OqoyzG8UhdZglSkOns_Zohj53hA",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/iO3OqoyzG8UhdZglSkOns_Zohj53hA.manifest",
        icon: "c3s2p.jpg",
        banner: "c3s2b.jfif",
      },
      {
        name: "20.00-CL-19532288",
        version: "++Fortnite+Release-20.00-CL-19532288-Windows",
        id: "z1z7_kWtA-qplo6njEKdDmZfgh8jXQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/z1z7_kWtA-qplo6njEKdDmZfgh8jXQ.manifest",
        icon: "c3s2p.jpg",
        banner: "c3s2b.jfif",
      },
      {
        name: "20.10-CL-19598943",
        version: "++Fortnite+Release-20.10-CL-19598943-Windows",
        id: "9fpTQALSrJBgGtbokkmsXKFGVbc7Dg",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/9fpTQALSrJBgGtbokkmsXKFGVbc7Dg.manifest",
        icon: "c3s2p.jpg",
        banner: "c3s2b.jfif",
      },
      {
        name: "20.20-CL-19751212",
        version: "++Fortnite+Release-20.20-CL-19751212-Windows",
        id: "IW78X73_lltKnT10HEWo0nd4qiQR7Q",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/IW78X73_lltKnT10HEWo0nd4qiQR7Q.manifest",
        icon: "c3s2p.jpg",
        banner: "c3s2b.jfif",
      },
      {
        name: "20.40-CL-20244966",
        version: "++Fortnite+Release-20.40-CL-20244966-Windows",
        id: "b0olgg0z0UhYUqjbukqGxSxCfxHNWQ",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/b0olgg0z0UhYUqjbukqGxSxCfxHNWQ.manifest",
        icon: "c3s2p.jpg",
        banner: "c3s2b.jfif",
      },
    ],
  },
  c3s3: {
    shortName: "c3s3",
    seasonName: "Chapter 3, Season 3",
    icon: "c3s3p.jpg",
    banner: "c3s3b.png",
    manifests: [
      {
        name: "21.00-CL-20463113",
        version: "++Fortnite+Release-21.00-CL-20463113-Windows",
        id: "BYoPt8OAt4JoMUHx9UC9ERHSMU776w",
        url: "https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/BYoPt8OAt4JoMUHx9UC9ERHSMU776w.manifest",
        icon: "c3s3p.jpg",
        banner: "c3s3b.jfif",
      },
    ],
  },
};
